import React, { useState, useEffect } from 'react';
import { BarChart3, TrendingUp, Award, DollarSign, Calendar } from 'lucide-react';
import { Bar, Doughnut, Line } from 'react-chartjs-2';
import { adminService } from '../../services/adminService';
import Loading from '../../components/Loading';

export const AdminReports = () => {
  const [analytics, setAnalytics] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAnalytics = async () => {
      setLoading(true);
      try {
        const data = await adminService.getAdminAnalytics();
        setAnalytics(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchAnalytics();
  }, []);

  if (loading) return <Loading message="Synthesizing intelligence reports and analytics..." />;

  const charts = analytics?.charts || {};
  const kpis = analytics?.kpis || {};
  const popularCategories = charts.popular_categories || [];

  // Bar Chart: Popular Categories
  const categoryBarData = {
    labels: popularCategories.map((c) => c.name),
    datasets: [
      {
        label: 'Booking Count',
        data: popularCategories.map((c) => c.count),
        backgroundColor: '#0284c7',
        borderRadius: 6,
      },
    ],
  };

  const categoryBarOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: {
        grid: { display: false },
        ticks: { color: '#94a3b8', maxRotation: 45, minRotation: 20 },
      },
      y: {
        grid: { color: 'rgba(255, 255, 255, 0.05)' },
        ticks: { color: '#94a3b8', precision: 0 },
      },
    },
  };

  // Line Chart: Revenue by Month
  const revenueLineData = {
    labels: charts.monthly_labels || [],
    datasets: [
      {
        label: 'Settled Revenue ($)',
        data: charts.monthly_revenue || [],
        borderColor: '#10b981',
        backgroundColor: 'rgba(16, 185, 129, 0.12)',
        tension: 0.35,
        fill: true,
        pointBackgroundColor: '#34d399',
        pointRadius: 5,
      },
    ],
  };

  return (
    <div>
      <div className="page-header">
        <div className="page-title">
          <h1>Analytics & Operational Reports</h1>
          <p>Key performance indicators, revenue velocity, and popular service packages.</p>
        </div>
      </div>

      {/* Summary Row */}
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-icon green"><DollarSign size={24} /></div>
          <div className="stat-details">
            <h3>${kpis.total_revenue?.toLocaleString() || '0'}</h3>
            <p>Total Revenue Billed</p>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon blue"><TrendingUp size={24} /></div>
          <div className="stat-details">
            <h3>${kpis.total_paid_collected?.toLocaleString() || '0'}</h3>
            <p>Cash Collected</p>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon purple"><Award size={24} /></div>
          <div className="stat-details">
            <h3>{kpis.completed_services || 0}</h3>
            <p>Services Completed</p>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon amber"><Calendar size={24} /></div>
          <div className="stat-details">
            <h3>{kpis.cancelled_services || 0}</h3>
            <p>Cancelled Services</p>
          </div>
        </div>
      </div>

      {/* Charts */}
      <div className="charts-grid" style={{ marginBottom: '2rem' }}>
        <div className="chart-card">
          <div className="chart-header">
            <h3>Most Popular Service Packages</h3>
          </div>
          <div style={{ height: '300px' }}>
            <Bar data={categoryBarData} options={categoryBarOptions} />
          </div>
        </div>

        <div className="chart-card">
          <div className="chart-header">
            <h3>Revenue Generated by Month</h3>
          </div>
          <div style={{ height: '300px' }}>
            <Line data={revenueLineData} options={{ responsive: true, maintainAspectRatio: false }} />
          </div>
        </div>
      </div>

      {/* Popular Categories Table */}
      <div className="card">
        <h3 style={{ marginBottom: '1.25rem' }}>Service Package Performance</h3>
        <div className="table-responsive">
          <table className="data-table">
            <thead>
              <tr>
                <th>Service Name</th>
                <th>Estimated Fee</th>
                <th>Completed Bookings</th>
                <th>Total Yield Estimate</th>
              </tr>
            </thead>
            <tbody>
              {popularCategories.map((c, i) => (
                <tr key={i}>
                  <td style={{ fontWeight: 700 }}>{c.name}</td>
                  <td>${c.cost}</td>
                  <td><span className="badge badge-assigned">{c.count} bookings</span></td>
                  <td style={{ fontWeight: 700, color: 'var(--success)' }}>
                    ${(c.cost * c.count).toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default AdminReports;
